import os
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CAPTURE_DIR = os.path.join(BASE_DIR, "captures")
MODEL_PATH = "yolov8n.pt"
CAMERA_INDEX = 0
RESOLUTION = (320, 240)
ROTATE_FRAME = None
CONF_THRESHOLD = 0.11
IMG_SZ = 320
DETECT_EVERY_N_FRAMES = 1
SMOOTH_WINDOW = 2
HUMAN_CONFIRM_COUNT = 1
RESET_ON_NO_HUMAN_CHECKS = 15
HUMAN_NAMES = {"person"}
ANIMAL_NAMES = {"dog", "cat", "horse", "sheep", "cow", "bear", "zebra"}
VEHICLE_NAMES = {"car", "truck", "bus", "bicycle", "motorcycle"}
TELEGRAM_TOKEN = "8739792864:AAF8QYlQrVd1Jimbi9qwK5EZI1V-zs3G-2Y"
TELEGRAM_CHAT_ID = "1762186586"
USE_MOTION_DETECTION = False
DETECTION_CACHE_SIZE = 20
MIN_DETECTION_INTERVAL = 0.03
ALERT_COOLDOWN = 8